### ISSUE TITLE
Is it really in cocoapods?

### ISSUE THREAD

**Issue by Joker666** [VoIPGRID/VialerSIPLib#1]
Can't find the library in cocoapods, pod install gives error "[!] Unable to find a specification for `VialerSIPLib`"

**Comment by m-vellinga** [comment]
Hello Joker666,

As far as I can tell you are right and it can not be found in Cocoapods. Sadly all our iOS developers are on holiday so I'll ask them to get back to you about this. Thanks for reporting this issue.

**Comment by SURENDRA7700** [comment]
hi
me too getting this issue while doing this and i did not find keys.h file ..it showing missing file it leads to error please resolve this issue

**Comment by Joker666** [comment]
+SURENDRA7700 keys.h is there as keys.sample.h you just have to rename it

**Comment by bobvoorneveld** [comment]
Hee Joker666. I'm so sorry for the wrong information. We haven't released it jet on cocoapods and still have it on our private repo. We'll be back in 2 weeks and first thing we'll do is put it on cocoapods.

**Comment by bobvoorneveld** [comment]
Hee Surendra7700, we've added an example file as joker666 mentioned. You keys.h file is git ignored to prevent leaking sip credentials. Just copy the file and add your own details.

**Comment by Joker666** [comment]
It's ok, I just copied the code and built the dependencies, so its working for me :) Would be great for others if its in Cocoapods. Enjoy vacation.

**Comment by SURENDRA7700** [comment]
HI

Keys.h provide file but specify credentials as names .file not found means
what we have to write is getting  difficult.

can you please send me the complied code successful

Because i am facing sip calling problem for using right SDK

hope you guys understand

Thank you

**Comment by SURENDRA7700** [comment]
![screen shot 2016-07-28 at 11 46 12 am](https://cloud.githubusercontent.com/assets/13854872/17202763/f61405fa-54b8-11e6-810d-39766954c146.png)
Rename `Keys.sample.h` from the Example/VialerSIPLib directory to Keys.h and add your personal credentials. You can now run a the library with a very basic UI.

here not display Keys.sample.h instead of that  showing  keys.h

**Comment by SURENDRA7700** [comment]
![screen shot 2016-07-28 at 11 49 40 am](https://cloud.githubusercontent.com/assets/13854872/17202845/6cf6900c-54b9-11e6-9574-76a7306d5b0d.png)

**Comment by m-vellinga** [comment]
@SURENDRA7700 That's a weird looking error. Our iOS dev team is not available right now due to holidays but they will look into it as soon as they're back. 

For any further comments or issues that are not related to Cocoapods, please open a new issue. Comments on this thread that are not related to this topic will be deleted in order to keep a clear overview. Thanks in advance.

**Comment by mohpor** [comment]
Any news on Cocoapods support?

P.S.: I hope everyone enjoyed their vacation 👍

**Comment by SURENDRA7700** [comment]
hI

every one i am doing r&d on sip calling functionality .please anyone help
me out .now i am work arounf restcommm .please any one help me sip
implementation

**Comment by mohpor** [comment]
A simple workaround for those still want to use Cocoapods to start using this library:  

This library is not up on public trunk of cocoapods but you can still add it using `:path` attribute in your pod file. All you need to do is to:

1. Clone this repository somewhere near your project.
2. Update your pod file to include this: `pod 'VialerSIPLib-iOS', :path => "../VialerSIPLib-iOS"` instead of the original `pod 'VialerSIPLib'` (Assuming you've cloned this repository into the immediate root folder of your current pod file)
3. Comment out `use_frameworks!`, i.e. `#use_frameworks!`
4. run a `pod update`

Enjoy the best SIP Client SDK there is (or will be!)

P.S. This library needs more attention from people who will actively develop against SIP. I'm sure with the help of everyone of us this will become a great library for an ugly thing that is SIP (yuk indeed) 😃

**Comment by bobvoorneveld** [comment]
To give an update on this issue. I'm working on setting the pod on cocoapods. Still some small issues, we'll keep you informed on this thread.

**Comment by bobvoorneveld** [comment]
Ok, I've put the lib on cocoapods. @SURENDRA7700, if you still have issues with the current version, please deintegrate and pod install again, that might help.
