### ISSUE TITLE
How to enable Opus codec?

### ISSUE THREAD

**Issue by smolskyaleksey** [VoIPGRID/VialerSIPLib#17]
I want to use Opus codec. How to enable it? I know it works from box. 
PJSIP version 2.5 is released with main focus on Opus codec and WebRTC AEC integrations. 

https://blog.pjsip.org/2016/05/11/pjsip-version-2-5-is-released-with-support-for-opus-and-webrtc-aec/

**Comment by smolskyaleksey** [comment]
If I understand correctly  
I should add` #define PJMEDIA_HAS_OPUS_CODEC  1` to section  `PJ_CONFIG_IPHONE` in

https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/Pod/vialer-pjsip-include/pj/config_site_sample.h

**Comment by bobvoorneveld** [comment]
I'm not sure what steps should be included. Couple of things that need to happen:
1. possible a recompile of the Vialer-pjsip-iOS pod (https://github.com/VoIPGRID/Vialer-pjsip-iOS) with that flag enabled
2. Something smart needs to happen in this method, in such a way that the codec is available in the negotiations: (https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLEndpoint.m#L380)

Aat the moment, we have a static list of a couple of codec in such a way that we think is the best codec first. As an optimization, we also included the flag onlyUseILBC, so that in the negotiations only that codec is a possibility. If you want to force the Opus codec, something similair should happen, otherwise the other party might prefer another codec.

If you're certain that the other party will always prefer Opus, adding Opus as a codec to the default list should be enough.

Checking the INVITES should make clear what codec has been chosen for the conversation.

Does that answer your question?

**Comment by smolskyaleksey** [comment]
Could you add OPUS to yours PJSIP lib? It has no effect on your version, but it will help other people to use other codecs.  if I understand correctly from https://trac.pjsip.org/repos/ticket/1904 need to download opus codec and add parameter
`--with-opus=[absolute-path-to]/opus-dev-lib` to 
https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/vialerbuild#L156

**Comment by bobvoorneveld** [comment]
Would you mind adding it your self and file a PR for Vialer-pjsip-iOS? We're willing to check if our project will run with the new build, but aren't able to test the codec. If nothing breaks, we will accept your PR. Please make sure the vialerbuildscript is updated so that the compilation can be reproduced when new versions of pjsip or other dependencies will emerge.

**Comment by bobvoorneveld** [comment]
#define PJMEDIA_HAS_OPUS_CODEC 1 can be added to config_site.h in the root folder, which is included by the build script.

**Comment by bobvoorneveld** [comment]
WIP: https://github.com/VoIPGRID/VialerSIPLib/pull/21
