### ISSUE TITLE
[Feature] G729 codec

### ISSUE THREAD

**Issue by c-Viorel** [VoIPGRID/VialerSIPLib#187]
### Version

Vialer-pjsip-iOS (3.4.1)
 VialerSIPLib (3.5.4)

### File / Feature

What are the chances that G729 codec to be available? I've looked into a previously closed issue and tried to follow those steps to include myself the codec but I failed. Also, I've searched for a solution but I could,t find anything useful. Do you have any starting point from where I could begin? 

### Expected behaviour

G729 codec to be available 

### Actual behaviour

G729 is not available

**Comment by jeremynorman89** [comment]
Quoting myself from when I closed the last issue about G729 (https://github.com/VoIPGRID/VialerSIPLib/issues/181):

> Unfortunately G729 is not supported by Vialer-pjsip-iOS even though I do see it enabled in some of the configuration files, it is not offering it as a valid codec.
> 
> As can be seen [in the VoiSmart pjsip builder](https://github.com/VoiSmart/pjsip-android-builder/tree/master/patches/support_g729) there are some hoops to jump through to get it to work, as well as licensing issues.
> 
> As we have no use for this codec and it's not just a matter of adding a couple of lines we won't be adding support for G729.

You would need to build PJSIP with G729 support and then use that binary instead of the one we are [pulling in via CocoaPods.](https://github.com/VoIPGRID/VialerSIPLib/blob/718507f57822258a2473c06b028d9f7c512470b2/VialerSIPLib.podspec#L30)
