### ISSUE TITLE
Support for media direction changes (Offer Negotiation using SDP)

### ISSUE THREAD

**Issue by brennanMKE** [VoIPGRID/VialerSIPLib#57]
### Version

2.5.0

### File / Feature

I am interested in support for negotiating a change for media direction using SDP which would involved changing the local offer and negotiating the change with the remote. Is there any plans on making this a feature within this library?

### Expected behaviour

Changing the session to send only or receive only from the default of send and receive would prevent audio (and video) from being send or received.

### Actual behaviour

The sessions default to send and receive.

### Stacktrace / Error message

None

### Other info

https://www.ietf.org/rfc/rfc3264.txt

**Comment by bobvoorneveld** [comment]
Hi, I'm not a expert in these kind of issues, but if I understand correct, is this something that we have disabled in PJSIP because our configuration with our Asterisk servers didn't work that way. In our supporting pod https://github.com/voipgrid/vialer-pjsip-ios we've set a parameter in https://github.com/VoIPGRID/Vialer-pjsip-iOS/blob/develop/config_site.h ->

// this version of PJSIP will no longer do symmetrical SDP negotiation, because with reinvites it will use its own numbering for codecs again
// and Asterisk will not adopt to those changes.
#define PJMEDIA_SDP_NEG_ANSWER_SYMMETRIC_PT 0

Setting this parameter for your build should work in you case. I'm not sure if recompiling the library is needed. Start by checking all references in config_site.h in your pods project and remove the flag and look if it works.
