### ISSUE TITLE
run background

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#94]
Hello @jvanveen  @Luit @hbokh @Shrikey @mvletter 
How do you keep this app alive in the background?
Can you help me?

**Comment by spindleredmer** [comment]
We have implemented a middleware solution (https://github.com/VoIPGRID/vialer-middleware). Since iOS9 apple is not really allowing to keep your app active in the background for VoIP apps. They have introduced the VoIP Push Notifications. This is a high priority push notification from Apple. To see an example on how this works you can check out Vialer (https://github.com/VoIPGRID/vialer-ios) that is our own implementation of this cocoapod.
